pointcloud_to_laserscan:
  ros__parameters:
    target_frame: base_link
    transform_tolerance: 0.15
    min_height: 0.20
    max_height: 1.25
    angle_min: -1.5751596
    angle_max: 1.5751596
    angle_increment: 0.0174533
    scan_time: 0.125
    range_min: 0.45
    range_max: 5.0
    use_inf: true
    inf_epsilon: 1.0
